name: periodsapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  table_calendar: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/women.png
    - assets/images/c.png
    - assets/images/i.png
    - assets/images/r.png
    - assets/images/l.png
    - assets/images/landing.png	
    - assets/images/home.png
    - assets/images/bell.png
    - assets/images/women.png
    - assets/images/profile.png
    - assets/images/settings.png